Projeto_final_abrigo/abrigo/urls.py
from django.contrib import admin
from django.urls import path
from app_adotantes.views import formulario_animal
from django.conf import settings
from django.conf.urls.static import static
from app_paginas_gerais.views import inicial, sobre
from app_animais.views import animal_list, animal_detail
from app_voluntarios.views import voluntarios
from django.urls import path
from app_animais.views import search_animais

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicial, name='inicial'),
    path('sobre/', sobre, name='sobre'),
    path('animal/<int:pk>/formulario', formulario_animal, name='formulario_animal'),
    path('animais/', animal_list, name='animais'),
    path('animais/<int:pk>/', animal_detail, name='animal_detail'),
    path('voluntarios/', voluntarios, name='voluntarios' ),
    path('search/', search_animais, name='search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )+ [
    # Definindo o caminho para servir arquivos estáticos durante o desenvolvimento
    # Isso serve arquivos estáticos em STATIC_URL (ex: '/static/') para STATIC_ROOT (ex: 'static/')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Projeto_final_abrigo/app_voluntarios/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

STATUS = (
    ('p', 'Pendente'),
    ('a', 'Aprovado'),
    ('r', 'Recusado'),
)

class Voluntario(models.Model):
    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    telefone = PhoneNumberField()
    profissão = models.CharField(max_length=500)
    info_geral = models.CharField('Informação', max_length=500)
    ativo = models.BooleanField(default=True)
    status = models.CharField(max_length=1,choices=STATUS, default="p")


    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name = 'Inscrição de voluntario'
        verbose_name_plural = 'Inscrição de voluntarios'

Projeto_final_abrigo/app_voluntarios/forms.py
from django import forms
from app_voluntarios.models import Voluntario

class VoluntariosForms(forms.ModelForm):
    class Meta:
        model = Voluntario
        fields = ['nome', 'email', 'telefone', 'profissão', 'info_geral']

    def clean(self):
        cleaned_data = super().clean()
        nome = cleaned_data.get('nome')
        email = cleaned_data.get('email')
        telefone = cleaned_data.get('telefone')
        profissao = cleaned_data.get('profissão')
        info_geral = cleaned_data.get('info_geral')

        if not nome:
            self.add_error('nome', 'Este campo é obrigatório.')
        if not email:
            self.add_error('email', 'Este campo é obrigatório.')
        if not telefone:
            self.add_error('telefone', 'Este campo é obrigatório.')
        if not profissao:
            self.add_error('profissão', 'Este campo é obrigatório.')
        if not info_geral:
            self.add_error('informações', 'Este campo é obrigatório.')

Projeto_final_abrigo/app_voluntarios/views.py
from django.shortcuts import render
from app_voluntarios.forms import VoluntariosForms

# Create your views here.
def voluntarios(request):
    if request.method == 'POST':
        form = VoluntariosForms(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'voluntarios.html', {'form': form, 'sucesso': True})
    else:
        form = VoluntariosForms()
    return render(request, 'voluntarios.html', {'form': form}) 

    

Projeto_final_abrigo/app_voluntarios/templates/voluntarios.html
{% extends 'base.html' %}
{% load static %}


    {% block content %}
    <link rel="stylesheet" type="text/css" href="{% static '/voluntarios/css/style.css' %}">
    
    <header class="header" >
        <img src="{% static '/voluntarios/img/header-voluntario.png' %}" class="header-voluntario" alt="Header"/>
      </header>
    
      
    <h1>Seja um voluntário e nos ajude a salvar vidas!</h1>

    <div class="conteiner">
        <div class="inf_voluntariado">
            <img src="{% static 'voluntarios/img/Component 1.png' %}" alt="">
        </div>

        <div class="inf_voluntariado">
            <h4>O que é um voluntário?</h4>
            <p class="text-voluntario">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde ducimus, sequi suscipit esse totam tempore quisquam blanditiis sint omnis, ipsa magni perferendis, facilis aut mollitia voluptatem placeat fugit provident. Beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis natus quaerat magni, nam temporibus obcaecati, nostrum quis deleniti eveniet minus est necessitatibus nulla sapiente impedit dicta. Ab temporibus corrupti natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam vitae sit perferendis iusto blanditiis dolor eum natus ea eveniet minima</p>

            <h4>O que um voluntário faz na Eniac Petz?</h4>
            <p class="text-voluntario">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde ducimus, sequi suscipit esse totam tempore quisquam blanditiis sint omnis, ipsa magni perferendis, facilis aut mollitia voluptatem placeat fugit provident. Beatae! Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis natus quaerat magni, nam temporibus obcaecati, nostrum quis deleniti eveniet minus est necessitatibus nulla sapiente impedit dicta. Ab temporibus corrupti natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam vitae sit perferendis iusto blanditiis dolor eum natus ea eveniet minima.</p>

            <h4>O que eu preciso para ser um voluntario na Eniac Petz?</h4>
            <p class="text-voluntario">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Unde ducimus, sequi suscipit esse totam tempore quisquam blanditiis.</p>
        </div>
    </div>
    
    <div class="form-voluntario1">
        <div>
            <img src="{% static '/voluntarios/img/Component 2.png' %}" alt="" class="form_voluntario">
        </div>
        <div class="caixa_fora">
            <div class="caixa_form">
                <h2 class="preencha">Preencha aqui seus dados!</h2>

                <form action="" method="POST" id="form">
                    {% csrf_token %}
                    <input type="text" name="nome" id="id_nome" placeholder="nome completo" class="nome_form">
                    <input type="email" name="email" id="id_email" placeholder="email" class="email_form">
                    <input type="tel" name="telefone" id="id_telefone" placeholder="telefone" class="tel_form">
                    <input type="text" name="profissão" id="id_profissão" placeholder="profissão" class="prof_form">
                    <input type="text" name="info_geral" id="id__informações" placeholder="informações adicionais" class="inf_form">
                    <button type="submit" id="botão_enviar">Quero ser voluntario</button>
                </form>
            </div>
        </div>
    </div>


    {% if sucesso %}
    <script>
        alert('Seu formulário foi enviado com sucesso.');
    </script>
    {% endif %}
     
{% endblock %}